---
title: "mbh_climate"
author: "Gabe Runte"
date: "2024-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prism)
library(tidyverse)
library(raster)
library(stringr)
library(magrittr)

prism_set_dl_dir('/Users/Gabe/Desktop/prism_data_monthly')
```


```{r}
get_prism_monthlys(type = "tmean", #can change type of data
                 years = 2000:2023,
                 keepZip = F)

get_prism_monthlys(type = "ppt", #can change type of data
                 years = 2000:2023,
                 keepZip = F)

```



```{r}

climate_data <- prism_archive_ls() %>%  
  pd_stack(.)  

site_names <- c("ang", "jdf", "ptr", "sql")
long <- c(-123.651971,-123.658124, -122.836923, -121.900927)
lat <- c(39.707698, 39.358927, 38.053113, 37.081977)

sites = tibble(site_names, long, lat)

locs = sites[,2:3]
ppt = raster::extract(climate_data, locs)


### change the pivot columns!
precip = as.data.frame(ppt) %>% tibble() %>% dplyr::select(1:24) %>%  
  mutate(site_names = sites$site_names) %>% 
  pivot_longer(cols = 1:24, names_to = "yr", values_to = "rain") %>% 
  mutate(yr = as.numeric(str_sub(yr, 24, 27)))

temp = as.data.frame(ppt) %>% tibble() %>% dplyr::select(25:48) %>%  
  mutate(site_names = sites$site_names) %>% 
  pivot_longer(cols = 1:24, names_to = "yr", values_to = "tmean") %>% 
  mutate(yr = as.numeric(str_sub(yr, 26, 29)))


ggplot(precip, aes(x = yr, y = rain, colour = site_names))+
  geom_line(alpha = 0.5)+geom_smooth(method = "lm", lty = 2, se = F)+
  scale_color_manual(name = "Site", labels = c("Angelo", "Jackson", "Point Reyes", "Soquel"),
                     values = c("#AF000D", "#FF8F00", "#0076FF", "#9B00F5"))+
  scale_x_continuous(breaks = c(2000, 2005, 2010, 2015, 2020, 2023))+labs(x = "Year", y = "Precipitation (mm)")+
  theme_minimal()
  

ggplot(temp, aes(x = yr, y = tmean, colour = site_names))+
  geom_line(alpha = 0.5)+geom_smooth(method = "lm", lty = 2, se = F)+
  scale_color_manual(name = "Site", labels = c("Angelo", "Jackson", "Point Reyes", "Soquel"),
                     values = c("#AF000D", "#FF8F00", "#0076FF", "#9B00F5"))+
  scale_x_continuous(breaks = c(2000, 2005, 2010, 2015, 2020, 2023))+labs(x = "Year", y = "Mean Temperature")+
  theme_minimal()
  
```


```{r}
site_data = precip %>% 
  left_join(temp) %>% 
  mutate(stress = tmean/rain)


ggplot(site_data, aes(x = yr, y = stress, colour = site_names))+
  geom_line(alpha = 0.5)+geom_smooth(method = "lm", lty = 2, se = F)+
  scale_color_manual(name = "Site", labels = c("Angelo", "Jackson", "Point Reyes", "Soquel"),
                     values = c("#AF000D", "#FF8F00", "#0076FF", "#9B00F5"))+
  scale_x_continuous(breaks = c(2000, 2005, 2010, 2015, 2020, 2023))+labs(x = "Year", y = "Evaporative stress (temp/rain)")+
  theme_minimal()+scale_y_log10()
```

